Description: GraphQl API
Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
  ResourceBucketName:
    Type: String
  AppSyncLogRoleArn:
    Type: String
  AppSyncResourceDynamoDbRoleArn:
    Type: String
  AppSyncResourceLambdaRoleArn:
    Type: String
  UserTableName:
    Type: String
  StreamTableName:
    Type: String
  UserInteractionTableName:
    Type: String
  LikeTableName:
    Type: String
  CommentTableName:
    Type: String
  FlagTableName:
    Type: String
  UncloggerPromptTableName:
    Type: String
  PlaceGetterFunctionArn:
    Type: String
  ResourceSearcherFunctionArn:
    Type: String
  RecaptchaTokenResolverFunctionArn:
    Type: String
Resources:
  # A P I
  AppSyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub "${ProjectIdentifierName}-appsync-api"
      AuthenticationType: API_KEY
      # UserPoolConfig: UserPoolConfig
      # OpenIDConnectConfig : OpenIDConnectConfig
      LogConfig:
        FieldLogLevel: ERROR
        CloudWatchLogsRoleArn: !Ref AppSyncLogRoleArn

  # S C H E M A
  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      DefinitionS3Location: !Sub "s3://${ResourceBucketName}/graphql/schema.graphql"

  # R E S O L V E R S
  # Query
  GetUserByUsernameResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getUserByUsername
      DataSourceName: !GetAtt AppSyncUserTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/getUserByUsername.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnList.resp.vm"

  ListStreamsByUserResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listStreamsByUser
      DataSourceName: !GetAtt AppSyncStreamTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/listStreamsByUser.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  ListLikesByUserResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listLikesByUser
      DataSourceName: !GetAtt AppSyncLikeTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/listLikesByUser.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  ListUserInteractionsByActorUserIdIndexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listUserInteractionsByActorUserIdIndex
      DataSourceName: !GetAtt AppSyncUserInteractionTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/listUserInteractionsByActorUserIdIndex.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  GetStreamResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getStream
      DataSourceName: !GetAtt AppSyncStreamTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/getStream.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  ListSealedStreamsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listSealedStreams
      DataSourceName: !GetAtt AppSyncStreamTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/listSealedStreams.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  ListLiveStreamsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listLiveStreams
      DataSourceName: !GetAtt AppSyncStreamTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/listLiveStreams.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  QueryUserInteractionsBetweenUsersByUserIdIndicesResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: queryUserInteractionsBetweenUsersByUserIdIndices
      DataSourceName: !GetAtt AppSyncUserInteractionTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/queryUserInteractionsBetweenUsersByUserIdIndices.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnList.resp.vm"

  ListStreamLikesResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listStreamLikes
      DataSourceName: !GetAtt AppSyncLikeTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/listStreamLikes.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnList.resp.vm"

  ListPaginatedStreamCommentsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listPaginatedStreamComments
      DataSourceName: !GetAtt AppSyncCommentTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/listPaginatedStreamComments.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  SearchResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: search
      DataSourceName: !GetAtt AppSyncResourceSearcherFunctionDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/lambda.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/search.resp.vm"

  GetRecaptchaTokenResultResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getRecaptchaTokenResult
      DataSourceName: !GetAtt AppSyncRecaptchaTokenResolverFunctionDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/lambda.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/lambda.resp.vm"

  # Mutations
  UpdateUserResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: updateUser
      DataSourceName: !GetAtt AppSyncUserTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/updateUser.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  DeleteUserResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteUser
      DataSourceName: !GetAtt AppSyncUserTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/deleteUser.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  CreateStreamResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: createStream
      DataSourceName: !GetAtt AppSyncStreamTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/createStream.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  UpdateStreamResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: updateStream
      DataSourceName: !GetAtt AppSyncStreamTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/updateStream.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  CreateUserInteractionResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: createUserInteraction
      DataSourceName: !GetAtt AppSyncUserInteractionTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/createUserInteraction.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  DeleteUserInteractionResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteUserInteraction
      DataSourceName: !GetAtt AppSyncUserInteractionTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/deleteUserInteraction.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  CreateLikeResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: createLike
      DataSourceName: !GetAtt AppSyncLikeTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/createLike.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  DeleteLikeResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteLike
      DataSourceName: !GetAtt AppSyncLikeTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/deleteLike.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  CreateCommentResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: createComment
      DataSourceName: !GetAtt AppSyncCommentTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/createComment.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  CreateFlagResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: createFlag
      DataSourceName: !GetAtt AppSyncFlagTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/createFlag.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  DeleteFlagResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteFlag
      DataSourceName: !GetAtt AppSyncFlagTableDataSource.Name
      RequestMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/deleteFlag.req.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${ResourceBucketName}/graphql/mappings/common/returnSingleItem.resp.vm"

  # D A T A   S O U R C E S
  AppSyncUserTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: user_ds
      Description: "The User Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref AppSyncResourceDynamoDbRoleArn
      DynamoDBConfig:
        TableName: !Ref UserTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncStreamTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: stream_ds
      Description: "The Stream Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref AppSyncResourceDynamoDbRoleArn
      DynamoDBConfig:
        TableName: !Ref StreamTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncUserInteractionTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: user_interaction_ds
      Description: "The UserInteraction Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref AppSyncResourceDynamoDbRoleArn
      DynamoDBConfig:
        TableName: !Ref UserInteractionTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncLikeTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: like_ds
      Description: "The Like Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref AppSyncResourceDynamoDbRoleArn
      DynamoDBConfig:
        TableName: !Ref LikeTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncCommentTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: comment_ds
      Description: "The Comment Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref AppSyncResourceDynamoDbRoleArn
      DynamoDBConfig:
        TableName: !Ref CommentTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncFlagTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: flag_ds
      Description: "The Flag Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref AppSyncResourceDynamoDbRoleArn
      DynamoDBConfig:
        TableName: !Ref FlagTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncUncloggerPromptTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: unclogger_prompt_ds
      Description: "The UncloggerPrompt Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref AppSyncResourceDynamoDbRoleArn
      DynamoDBConfig:
        TableName: !Ref UncloggerPromptTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncPlaceGetterFunctionDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: place_getter_ds
      Description: "The Place-Getter Function AppSync Data Source"
      Type:  AWS_LAMBDA
      ServiceRoleArn: !Ref AppSyncResourceLambdaRoleArn
      LambdaConfig:
        LambdaFunctionArn: !Ref PlaceGetterFunctionArn

  AppSyncResourceSearcherFunctionDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: resource_searcher_ds
      Description: "The Resource-Searcher Function AppSync Data Source"
      Type:  AWS_LAMBDA
      ServiceRoleArn: !Ref AppSyncResourceLambdaRoleArn
      LambdaConfig:
        LambdaFunctionArn: !Ref ResourceSearcherFunctionArn

  AppSyncRecaptchaTokenResolverFunctionDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: recaptcha_token_resolver_ds
      Description: "The Recaptcha-Token-Resolver Function AppSync Data Source"
      Type:  AWS_LAMBDA
      ServiceRoleArn: !Ref AppSyncResourceLambdaRoleArn
      LambdaConfig:
        LambdaFunctionArn: !Ref RecaptchaTokenResolverFunctionArn
