Description:
  This template creates build projects
Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
  BranchName:
    Type: String
  PostConfirmUserImportFunctionRepositoryName:
    Type: String
  LambdaArtifactStoreBucket:
    Type: String
  UserTable:
    Type: String
  CognitoUserPoolId:
    Type: String
  CodeCommitRepoCodeBuildRoleArn:
    Type: String
  CodeCommitRepoCodePipelineRoleArn:
    Type: String
  LambdaManagerCloudFormationRoleArn:
    Type: String
Resources:
  PostConfirmUserImportFunctionBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-postconfirmuserimportfunction-build-project"
      Description: Used to build Cognito Post Confirmation User Import function from the CodeCommit Repo
      TimeoutInMinutes: 10
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/python:3.7.1"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: FUNCTION_NAME
            Value: !Sub "${ProjectIdentifierName}-post-confirm-user-importer-func"
          - Name: LAMBDA_ARTIFACT_STORE_BUCKET
            Value: !Ref LambdaArtifactStoreBucket
          - Name: USER_TABLE_NAME
            Value: !Ref UserTable
          - Name: COGNITO_USER_GROUP_NAME
            Value: !Sub "${ProjectIdentifierName}-${EnvironmentName}-users"
          - Name: COGNITO_USER_POOL_ID
            Value: !Ref CognitoUserPoolId
          - NAME: FUNCTION_ROLE_ARN
            Value: !Ref CognitoTriggeredLambdaRoleArn
          - Name: ENVIRONMENT_TAG
            Value: !Ref EnvironmentName
          - Name: APPLICATION_TAG
            Value: !Ref ProjectIdentifierName
      ServiceRole: !Ref CodeCommitRepoCodeBuildRoleArn

  PostConfirmUserImportFunctionPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-postconfirmuserimportfunction-pipeline"
      RoleArn: !Ref CodeCommitRepoCodePipelineRoleArn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: FetchSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref PostConfirmUserImportFunctionRepositoryName
                BranchName: !Ref BranchName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildFunction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref PostConfirmUserImportFunctionBuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: App
              RunOrder: 1
        - Name: Pipeline
          Actions:
            - Name: DeployPipeline
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-postconfirm-user-importer-function-pipeline-stack"
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                TemplatePath: "BuildArtifact::postconfirm-user-importer-output-template.yaml"
                RoleArn: !Ref LambdaManagerCloudFormationRoleArn
                ParameterOverrides: !Sub '{"RepositoryName": "${PostConfirmUserImportFunctionRepositoryName}", "BranchName": "${BranchName}"}'
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
