Description:
  This template creates build projects
Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
  FunctionName:
    Type: String
  BranchName:
    Type: String
  PostConfirmUserImportFunctionRepositoryName:
    Type: String
  LambdaArtifactStoreBucket:
    Type: String
  UserTable:
    Type: String
  CodeCommitRepoCodeBuildRoleArn:
    Type: String
  CodeCommitRepoCodePipelineRoleArn:
    Type: String
  LambdaManagerCloudFormationRoleArn:
    Type: String
  CognitoTriggeredLambdaRoleArn:
    Type: String
Resources:
  PostConfirmUserImportFunctionBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectIdentifierName}-cognito-user-exporter-func-build-proj"
      Description: Used to build Cognito Post Confirmation User Import function from the CodeCommit Repo
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/python:3.7.1"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: LAMBDA_ARTIFACT_STORE_BUCKET
            Value: !Ref LambdaArtifactStoreBucket
          - Name: USER_TABLE_NAME
            Value: !Ref UserTable
          - Name: COGNITO_USER_GROUP_NAME
            Value: !Sub "${ProjectIdentifierName}-${EnvironmentName}-users"
          - Name: ENVIRONMENT_TAG
            Value: !Ref EnvironmentName
          - Name: APPLICATION_TAG
            Value: !Ref ProjectIdentifierName
      ServiceRole: !Ref CodeCommitRepoCodeBuildRoleArn

  PostConfirmUserImportFunctionPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectIdentifierName}-user-exporter-pipeline"
      RoleArn: !Ref CodeCommitRepoCodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref LambdaArtifactStoreBucket
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: FetchSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOut
              Configuration:
                RepositoryName: !Ref PostConfirmUserImportFunctionRepositoryName
                BranchName: !Ref BranchName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildFunction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref PostConfirmUserImportFunctionBuildProject
              InputArtifacts:
                - Name: SourceOut
              OutputArtifacts:
                - Name: BuildOut
              RunOrder: 1
        - Name: Pipeline
          Actions:
            - Name: DeployPipeline
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                StackName: !Sub "${ProjectIdentifierName}-user-exporter-pipeline"
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: "BuildOut::output-template.yaml"
                RoleArn: !Ref LambdaManagerCloudFormationRoleArn
                # ParameterOverrides: !Sub '{"RepositoryName": "${PostConfirmUserImportFunctionRepositoryName}", "BranchName": "${BranchName}"}'
              InputArtifacts:
                - Name: BuildOut
              RunOrder: 1


