Description:
  This template deploys Cognito User and Identity Pools
Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
  SnsRoleArn:
    Type: String
  UserTableName:
    Type: String
  CognitoTriggeredLambdaRoleArn:
    Type: String

Resources:
  # Creates a User Pool
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-up"
      MfaConfiguration: "OFF"
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
      AliasAttributes:
        - 'email'
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

      # SMS
      SmsVerificationMessage: Your verification code is {####}
      SmsConfiguration:
        ExternalId: !Sub "${ProjectIdentifierName}-external-id"
        SnsCallerArn: !Ref SnsRoleArn

      # Email
      EmailVerificationMessage: Your verification code is {####}
      EmailVerificationSubject: !Sub "${ProjectIdentifierName} verification code"

      # Triggered Lambda
      LambdaConfig:
        PostConfirmation: !GetAtt CognitoPostConfirmationFunction.Arn

  # Creates a User Pool Client to be used by the identity pool
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-up-client"
      GenerateSecret: false
      UserPoolId: !Ref UserPool

  # Creates a federeated Identity pool
  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-ip"
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # Assigns the roles to the Identity Pool
  CognitoUnauthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: "CognitoUnauthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                Resource: "*"
  CognitoAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: "CognitoAuthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"
  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthorizedRole.Arn
        unauthenticated: !GetAtt CognitoUnauthorizedRole.Arn

  # Post Confirmation Trigger
  CognitoPostConfirmationFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
        S3Key:
        Version:
      Description: Moves user to DynamoDB UserTable upon conformation
      Environment:
        Variables:
          DB_USER_TABLE_NAME: !Ref UserTableName
          COGNITO_USER_GROUP_NAME: !Sub "${ProjectIdentifierName}-${EnvironmentName}-users"
          COGNITO_USER_POOL_ID: !Ref UserPool

      FunctionName: "${ProjectIdentifierName}-post-confirm-user-importer"
      Handler: "lambda_function.lambda_handler"
      MemorySize: 128
      Role: !Ref CognitoTriggeredLambdaRoleArn
      Runtime: python3.7
      Timeout: 3
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName
  # Attach User Pool the permission to trigger CognitoPostConfirmationFunction
  CognitoPostConfirmationFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CognitoPostConfirmationFunction.Arn
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !GetAtt UserPool.Arn

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-up-id"
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-upc-id"
  IdentityPoolId:
    Value: !Ref IdentityPool
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-ip-id"
