Description: This template deploys Datasources for the app

Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
  ApprovalDbClusterIdentifier:
    Type: String
  ApprovalDbName:
    Type: String
  InteractionDbClusterIdentifier:
    Type: String
  InteractionDbName:
    Type: String
  AuroraMysqlEngineVersion:
    Type: String
  AuroraMysqlMasterUsername:
    Type: String
  AuroraMysqlMasterUserPassword:
    Type: String
  AuroraMysqlDBSubnetGroupNames:
    Type: CommaDelimitedList

Mappings: 
  SecondaryIndexMap: 
    UserTable: 
      UserNameIndex: username-index
    CantoTable: 
      IsPausedLastUpdateTimeIndex: isPaused-lastUpdateTime-index
    StreamTable: 
      UserIdIndex: userId-index
      IsSealedSealTimeIndex: isSealed-sealTime-index
      IsSealedStartTimeIndex: isSealed-startTime-index

Resources:
  # DynamoDb
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${EnvironmentName}_Users
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !FindInMap [SecondaryIndexMap, UserTable, UserNameIndex]
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: Name
          Value: Users
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

  CantoTable:
    DependsOn: UserTable
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${EnvironmentName}_Cantos
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "isPaused"
          AttributeType: "N"
        - AttributeName: "lastUpdateTime"
          AttributeType: "S"
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !FindInMap [SecondaryIndexMap, CantoTable, IsPausedLastUpdateTimeIndex]
          KeySchema:
            - AttributeName: isPaused
              KeyType: HASH
            - AttributeName: lastUpdateTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: Name
          Value: Cantos
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

  StreamTable:
    DependsOn: CantoTable
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${EnvironmentName}_Streams
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "isSealed"
          AttributeType: "N"
        - AttributeName: "startTime"
          AttributeType: "S"
        - AttributeName: "sealTime"
          AttributeType: "S"
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !FindInMap [SecondaryIndexMap, StreamTable, UserIdIndex]
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: !FindInMap [SecondaryIndexMap, StreamTable, IsSealedSealTimeIndex]
          KeySchema:
            - AttributeName: isSealed
              KeyType: HASH
            - AttributeName: sealTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: !FindInMap [SecondaryIndexMap, StreamTable, IsSealedStartTimeIndex]
          KeySchema:
            - AttributeName: isSealed
              KeyType: HASH
            - AttributeName: startTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: Name
          Value: Streams
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

  # DBSubnet Group
  ApprovalDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Approval DB Subnet Group
      SubnetIds: !Ref AuroraMysqlDBSubnetGroupNames
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

  InteractionDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Interaction DB Subnet Group
      SubnetIds: !Ref AuroraMysqlDBSubnetGroupNames
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

  # Serverless Aurora DB Cluster
  ApprovalDbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      EngineVersion: !Ref AuroraMysqlEngineVersion
      DatabaseName: !Ref ApprovalDbName
      MasterUsername: !Ref AuroraMysqlMasterUsername
      MasterUserPassword: !Ref AuroraMysqlMasterUserPassword
      DBClusterIdentifier: !Ref ApprovalDbClusterIdentifier
      BackupRetentionPeriod: 7
      DeletionProtection: false
      EnableHttpEndpoint: true
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
        SecondsUntilAutoPause: 300
      DBSubnetGroupName: !Ref ApprovalDBSubnetGroup
      Tags:
        - Key: Name
          Value: Approval
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

  InteractionDbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      EngineVersion: !Ref AuroraMysqlEngineVersion
      DatabaseName: !Ref InteractionDbName
      MasterUsername: !Ref AuroraMysqlMasterUsername
      MasterUserPassword: !Ref AuroraMysqlMasterUserPassword
      DBClusterIdentifier: !Ref InteractionDbClusterIdentifier
      BackupRetentionPeriod: 7
      DeletionProtection: false
      EnableHttpEndpoint: true
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
        SecondsUntilAutoPause: 300
      DBSubnetGroupName: !Ref InteractionDBSubnetGroup
      Tags:
        - Key: Name
          Value: Interaction
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

Outputs:
  # DynamoDB
  UserTable:
    Description: A reference to the created UserTable
    Value: !Ref UserTable
  CantoTable:
    Description: A reference to the created CantoTable
    Value: !Ref CantoTable
  StreamTable:
    Description: A reference to the created StreamTable
    Value: !Ref StreamTable
  UserTableArn:
    Description: A reference to the created UserTable ARN
    Value: !GetAtt UserTable.Arn
  CantoTableArn:
    Description: A reference to the created CantoTable ARN
    Value: !GetAtt CantoTable.Arn
  StreamTableArn:
    Description: A reference to the created StreamTable ARN
    Value: !GetAtt StreamTable.Arn
  StreamTableIsSealedStartTimeIndex:
    Description: A reference to the created StreamTable Secondary Index is-sealed-start-time-index
    Value: !FindInMap [SecondaryIndexMap, StreamTable, IsSealedStartTimeIndex]

  # Relational
  ApprovalDbCluster:
    Description: A reference to the created ApprovalDbCluster i.e. its name
    Value: !Ref ApprovalDbCluster
  ApprovalDbClusterEndpointAddress:
    Description: A reference to the created ApprovalDbCluster endpoint address
    Value: !GetAtt ApprovalDbCluster.Endpoint.Address
  ApprovalDbClusterEndpointPort:
    Description: A reference to the created ApprovalDbCluster endpoint port
    Value: !GetAtt ApprovalDbCluster.Endpoint.Port
  InteractionDbCluster:
    Description: A reference to the created InteractionDbCluster i.e. its name
    Value: !Ref InteractionDbCluster
  InteractionDbClusterEndpointAddress:
    Description: A reference to the created InteractionDbCluster endpoint address
    Value: !GetAtt InteractionDbCluster.Endpoint.Address
  InteractionDbClusterEndpointPort:
    Description: A reference to the created InteractionDbCluster endpoint port
    Value: !GetAtt InteractionDbCluster.Endpoint.Port
