Description:
  This template deploys Datasources for the app

Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String

Resources:
  # DynamoDb
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: username-index
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: Name
          Value: Users
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

  # StreamTable:
  #   DependsOn: UserTable
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Streams
  #     BillingMode: PROVISIONED
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #       - AttributeName: "userId"
  #         AttributeType: "S"
  #       - AttributeName: "isSealed"
  #         AttributeType: "N"
  #       - AttributeName: "startTime"
  #         AttributeType: "S"
  #       - AttributeName: "sealTime"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: userId-index
  #         KeySchema:
  #           - AttributeName: userId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #       - IndexName: isSealed-sealTime-index
  #         KeySchema:
  #           - AttributeName: isSealed
  #             KeyType: HASH
  #           - AttributeName: sealTime
  #             KeyType: RANGE
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #       - IndexName: isSealed-startTime-index
  #         KeySchema:
  #           - AttributeName: isSealed
  #             KeyType: HASH
  #           - AttributeName: startTime
  #             KeyType: RANGE
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1
  #     Tags:
  #       - Key: Name
  #         Value: Streams
  #       - Key: Environment
  #         Value: !Ref EnvironmentName
  #       - Key: Application
  #         Value: !Ref ProjectIdentifierName

  # UserInteractionTable:
  #   DependsOn: StreamTable
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: UserInteractions
  #     BillingMode: PROVISIONED
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #       - AttributeName: "targetUserId"
  #         AttributeType: "S"
  #       - AttributeName: "actorUserId"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: targetUserId-index
  #         KeySchema:
  #           - AttributeName: targetUserId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #       - IndexName: actorUserId-index
  #         KeySchema:
  #           - AttributeName: actorUserId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1
  #     Tags:
  #       - Key: Name
  #         Value: UserInteractions
  #       - Key: Environment
  #         Value: !Ref EnvironmentName
  #       - Key: Application
  #         Value: !Ref ProjectIdentifierName

  # StreamCommentTable:
  #   DependsOn: UserInteractionTable
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: StreamComments
  #     BillingMode: PROVISIONED
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #       - AttributeName: "streamId"
  #         AttributeType: "S"
  #       - AttributeName: "userId"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: streamId-index
  #         KeySchema:
  #           - AttributeName: streamId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #       - IndexName: userId-index
  #         KeySchema:
  #           - AttributeName: userId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1
  #     Tags:
  #       - Key: Name
  #         Value: StreamComments
  #       - Key: Environment
  #         Value: !Ref EnvironmentName
  #       - Key: Application
  #         Value: !Ref ProjectIdentifierName

  # StreamLikeTable:
  #   DependsOn: StreamCommentTable
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: StreamLikes
  #     BillingMode: PROVISIONED
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #       - AttributeName: "streamId"
  #         AttributeType: "S"
  #       - AttributeName: "userId"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: streamId-index
  #         KeySchema:
  #           - AttributeName: streamId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #       - IndexName: userId-index
  #         KeySchema:
  #           - AttributeName: userId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1
  #     Tags:
  #       - Key: Name
  #         Value: StreamLikes
  #       - Key: Environment
  #         Value: !Ref EnvironmentName
  #       - Key: Application
  #         Value: !Ref ProjectIdentifierName

  # FlagTable:
  #   DependsOn: StreamLikeTable
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Flags
  #     BillingMode: PROVISIONED
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #       - AttributeName: "streamId"
  #         AttributeType: "S"
  #       - AttributeName: "commentId"
  #         AttributeType: "S"
  #       - AttributeName: "userId"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: streamId-index
  #         KeySchema:
  #           - AttributeName: streamId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #       - IndexName: commentId-index
  #         KeySchema:
  #           - AttributeName: commentId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #       - IndexName: userId-index
  #         KeySchema:
  #           - AttributeName: userId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1
  #     Tags:
  #       - Key: Name
  #         Value: Flags
  #       - Key: Environment
  #         Value: !Ref EnvironmentName
  #       - Key: Application
  #         Value: !Ref ProjectIdentifierName

  # UncloggerPromptTable:
  #   DependsOn: FlagTable
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: UncloggerPrompts
  #     BillingMode: PROVISIONED
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #       - AttributeName: "category"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: category-index
  #         KeySchema:
  #           - AttributeName: category
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1
  #     Tags:
  #       - Key: Name
  #         Value: UncloggerPrompts
  #       - Key: Environment
  #         Value: !Ref EnvironmentName
  #       - Key: Application
  #         Value: !Ref ProjectIdentifierName

  # Lambda

Outputs:
  UserTable:
    Description: A reference to the created UserTable
    Value: !Ref UserTable
  # StreamTable:
  #   Description: A reference to the created StreamTable
  #   Value: !Ref StreamTable
  # UserInteractionTable:
  #   Description: A reference to the created UserInteractionTable
  #   Value: !Ref UserInteractionTable
  # StreamCommentTable:
  #   Description: A reference to the created StreamCommentTable
  #   Value: !Ref StreamCommentTable
  # StreamLikeTable:
  #   Description: A reference to the created StreamLikeTable
  #   Value: !Ref StreamLikeTable
  # FlagTable:
  #   Description: A reference to the created FlagTable
  #   Value: !Ref FlagTable
  # UncloggerPromptTable:
  #   Description: A reference to the created UncloggerPromptTable
  #   Value: !Ref UncloggerPromptTable

  UserTableArn:
    Description: A reference to the created UserTable ARN
    Value: !GetAtt UserTable.Arn
  # StreamTableArn:
  #   Description: A reference to the created StreamTable ARN
  #   Value: !GetAtt StreamTable.Arn
  # UserInteractionTableArn:
  #   Description: A reference to the created UserInteractionTable ARN
  #   Value: !GetAtt UserInteractionTable.Arn
  # StreamCommentTableArn:
  #   Description: A reference to the created StreamCommentTable ARN
  #   Value: !GetAtt StreamCommentTable.Arn
  # StreamLikeTableArn:
  #   Description: A reference to the created StreamLikeTable ARN
  #   Value: !GetAtt StreamLikeTable.Arn
  # FlagTableArn:
  #   Description: A reference to the created FlagTable ARN
  #   Value: !GetAtt FlagTable.Arn
  # UncloggerPromptTableArn:
  #   Description: A reference to the created UncloggerPromptTable ARN
  #   Value: !GetAtt UncloggerPromptTable.Arn
