Description:
  This template deploys IAM roles for the application

Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String

Resources:
  # ROLES
  # Creates a role that allows Cognito to send SNS messages
  SNSRole:
    # Specifying a RoleName, you cannot perform updates that require replacement of this resource. You can perform updates that require no or some interruption. If you must replace the resource, specify a new name.
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "cognito-idp.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-cognito-sns-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "sns:publish"
                Resource: "*"

  LambdaManagerCloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'cloudformation.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'

  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-internal-codepipeline-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codecommit:CancelUploadArchive'
                  - 'codecommit:GetBranch'
                  - 'codecommit:GetCommit'
                  - 'codecommit:GetUploadArchiveStatus'
                  - 'codecommit:UploadArchive'
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                  - 'devicefarm:ListProjects'
                  - 'devicefarm:ListDevicePools'
                  - 'devicefarm:GetRun'
                  - 'devicefarm:GetUpload'
                  - 'devicefarm:CreateUpload'
                  - 'devicefarm:ScheduleRun'
                  - 'lambda:InvokeFunction'
                  - 'lambda:ListFunctions'
                  - 'iam:PassRole'
                  - 'elasticbeanstalk:*'
                  - 'ec2:*'
                  - 'elasticloadbalancing:*'
                  - 'autoscaling:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'rds:*'
                  - 'sqs:*'
                  - 'ecs:*'
                Resource: '*'

  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codebuild.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Policies:
      - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-internal-codebuild-policy"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            Resource: '*'
          - Effect: Allow
            Action: 'codecommit:GitPull'
            Resource: '*'
          - Effect: Allow
            Action:
            - 's3:GetObject'
            - 's3:GetObjectVersion'
            Resource: '*'
          - Effect: 'Allow'
            Action: 's3:PutObject'
            Resource: '*'

  CognitoTriggeredLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-cognito-triggered-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cognito-idp:*"
                  - "cognito-identity:*"
                  - "logs:*"
                  - "dynamodb:*"
                Resource: "*"

Outputs:
  SNSRole:
    Description: A reference to the created SNS Role
    Value: !Ref SNSRole
  LambdaManagerCloudFormationRole:
    Description: A reference to the created Lambda Managing CloudFormation Role
    Value: !Ref LambdaManagerCloudFormationRole
  CodePipelineRole:
    Description: A reference to the created Code Pipeline Role
    Value: !Ref CodePipelineRole
  CodeBuildRole:
    Description: A reference to the created Code Build Role
    Value: !Ref CodeBuildRole
  CognitoTriggeredLambdaRole:
    Description: A reference to the created Cognito Triggered Lambda Role
    Value: !Ref CognitoTriggeredLambdaRole
  SNSRoleArn:
    Description: A reference to the created SNS Role ARN
    Value: !GetAtt SNSRole.Arn
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-sns-role-arn"
  LambdaManagerCloudFormationRoleArn:
    Description: A reference to the created Lambda managing CloudFormation Role ARN
    Value: !GetAtt LambdaManagerCloudFormationRole.Arn
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-lambda-mgmt-cfn-role-arn"
  CodePipelineRoleArn:
    Description: A reference to the created Code Pipeline Role ARN
    Value: !GetAtt CodePipelineRole.Arn
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-internal-codepipeline-role-arn"
  CodeBuildRoleArn:
    Description: A reference to the created Code Build Role ARN
    Value: !GetAtt CodeBuildRole.Arn
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-internal-codebuild-role-arn"
  CognitoTriggeredLambdaRoleArn:
    Description: A reference to the created Cognito Triggered Lambda Role ARN
    Value: !GetAtt CognitoTriggeredLambdaRole.Arn
    Export:
      Name: !Sub "${ProjectIdentifierName}-${EnvironmentName}-cognito-triggered-lambda-role-arn"
