Description: This template deploys IAM roles for the application

Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
  ApprovalDbClusterIdentifier:
    Type: String
  InteractionDbClusterIdentifier:
    Type: String

Resources:

  LambdaManagerCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-lambdamanager-cfn-role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cloudformation:*"
                  - "iam:*"
                  - "events:*"
                  - "lambda:*"
                Resource: "*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-internal-codepipeline-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "codecommit:CancelUploadArchive"
                  - "codecommit:GetBranch"
                  - "codecommit:GetCommit"
                  - "codecommit:GetUploadArchiveStatus"
                  - "codecommit:UploadArchive"
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:RegisterApplicationRevision"
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                  - "devicefarm:ListProjects"
                  - "devicefarm:ListDevicePools"
                  - "devicefarm:GetRun"
                  - "devicefarm:GetUpload"
                  - "devicefarm:CreateUpload"
                  - "devicefarm:ScheduleRun"
                  - "lambda:InvokeFunction"
                  - "lambda:ListFunctions"
                  - "iam:PassRole"
                  - "elasticbeanstalk:*"
                  - "ec2:*"
                  - "elasticloadbalancing:*"
                  - "autoscaling:*"
                  - "cloudwatch:*"
                  - "s3:*"
                  - "sns:*"
                  - "cloudformation:*"
                  - "rds:*"
                  - "sqs:*"
                  - "ecs:*"
                Resource: "*"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-internal-codebuild-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: Allow
                Action: "codecommit:GitPull"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                Resource: "*"
              - Effect: "Allow"
                Action: "s3:PutObject"
                Resource: "*"

  AppSyncLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-appsync-logs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  AppSyncResourceDynamoDbRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-appsync-dynamodb-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:DeleteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:UpdateItem"
                Resource: "*"

  AppSyncResourceAuroraRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-appsync-aurora-rds-data-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "rds-data:DeleteItems"
                  - "rds-data:ExecuteSql"
                  - "rds-data:ExecuteStatement"
                  - "rds-data:GetItems"
                  - "rds-data:InsertItems"
                  - "rds-data:UpdateItems"
                Resource:
                  - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${ApprovalDbClusterIdentifier}"
                  - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${ApprovalDbClusterIdentifier}:*"
                  - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${InteractionDbClusterIdentifier}"
                  - !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${InteractionDbClusterIdentifier}:*"
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: "*"

  AppSyncResourceLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-appsync-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "lambda:InvokeFunction"
                Resource: "*"

Outputs:
  LambdaManagerCloudFormationRole:
    Description: A reference to the created Lambda Managing CloudFormation Role
    Value: !Ref LambdaManagerCloudFormationRole
  CodePipelineRole:
    Description: A reference to the created Code Pipeline Role
    Value: !Ref CodePipelineRole
  CodeBuildRole:
    Description: A reference to the created Code Build Role
    Value: !Ref CodeBuildRole
  AppSyncLogRole:
    Description: A reference to the created AppSync CloudWatch Logs Role
    Value: !Ref AppSyncLogRole
  AppSyncResourceDynamoDbRole:
    Description: A reference to the created AppSync DyanmoDB Role
    Value: !Ref AppSyncResourceDynamoDbRole
  AppSyncResourceAuroraRole:
    Description: A reference to the created AppSync Aurora Role
    Value: !Ref AppSyncResourceAuroraRole
  AppSyncResourceLambdaRole:
    Description: A reference to the created AppSync Lambda Role
    Value: !Ref AppSyncResourceLambdaRole
  LambdaManagerCloudFormationRoleArn:
    Description: A reference to the created Lambda managing CloudFormation Role ARN
    Value: !GetAtt LambdaManagerCloudFormationRole.Arn
  CodePipelineRoleArn:
    Description: A reference to the created Code Pipeline Role ARN
    Value: !GetAtt CodePipelineRole.Arn
  CodeBuildRoleArn:
    Description: A reference to the created Code Build Role ARN
    Value: !GetAtt CodeBuildRole.Arn
  AppSyncLogRoleArn:
    Description: A reference to the created AppSync CloudWatch Logs Role ARN
    Value: !GetAtt AppSyncLogRole.Arn
  AppSyncResourceDynamoDbRoleArn:
    Description: A reference to the created AppSync DynamoDB Role ARN
    Value: !GetAtt AppSyncResourceDynamoDbRole.Arn
  AppSyncResourceAuroraRoleArn:
    Description: A reference to the created AppSync Aurora Role ARN
    Value: !GetAtt AppSyncResourceAuroraRole.Arn
  AppSyncResourceLambdaRoleArn:
    Description: A reference to the created AppSync Lambda Role ARN
    Value: !GetAtt AppSyncResourceLambdaRole.Arn
