Description:
  This template deploys S3 buckets
Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
  LambdaFunctionArtifactStoreBucketName:
    Type: String
Resources:

  # Buckets
  FunctionDeploymentsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref LambdaFunctionArtifactStoreBucketName
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName
      VersioningConfiguration:
        Status: Enabled

  # Policies
  FunctionDeploymentsBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref FunctionDeploymentsBucket
      PolicyDocument:
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Action:
              - "s3:*"
            Resource: !Join [ "", [ !GetAtt FunctionDeploymentsBucket.Arn, "/*" ] ]
            Principal: "*"
            Condition:
              Bool:
                "aws:SecureTransport": false

Outputs:
  FunctionDeploymentsBucket:
    Description: A reference to the created FunctionDeploymentsBucket
    Value: !Ref FunctionDeploymentsBucket
