Resources:
  # Lambda Triggering
  UserPoolClientLambdaPolicy:
  # Sets userpool policy for the role that executes the Userpool Client Lambda
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-up-client-lambda-policy"
      Roles: 
        - Fn::ImportValue: 
            !Sub "${ProjectIdentifierName}-${EnvironmentName}-cognito-up-client-lambda-role-arn"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'cognito-idp:DescribeUserPoolClient'
            Resource: !GetAtt UserPool.Arn
    DependsOn: UserPoolClientLambda
  UserPoolClientLambdaLogPolicy:
  # Sets log policy for the role that executes the Userpool Client Lambda
  # Marked as depending on UserPoolClientLambdaPolicy for easier to understand CFN sequencing
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub "${ProjectIdentifierName}-${EnvironmentName}-up-client-lambda-log-policy"
      Roles: 
        - Fn::ImportValue: 
            !Sub "${ProjectIdentifierName}-${EnvironmentName}-cognito-up-client-lambda-role-arn"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: !Sub  
              - arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
              - { region: !Ref "AWS::Region", account: !Ref "AWS::AccountId", lambda: !Ref UserPoolClientLambda}
    DependsOn: UserPoolClientLambdaPolicy 
  UserPoolClientInputs:
  # Values passed to Userpool client Lambda
  # Marked as depending on UserPoolClientLambdaPolicy for easier to understand CFN sequencing
    Type: 'Custom::LambdaCallout'
    Properties:
      ServiceToken: !GetAtt UserPoolClientLambda.Arn
      clientId: !Ref UserPoolClient
      userpoolId: !Ref UserPool
    DependsOn: UserPoolClientLambdaLogPolicy