Description: Deploys Route53 and Cloudfront
Parameters:
  ProjectIdentifierName:
    Type: String
  EnvironmentName:
    Type: String
Resources:
  HostingBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy": "Retain"
    Properties:
      BucketName: !Sub "${ProjectIdentifierName}-hosting"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - Authorization
              - Content-Length
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
            MaxAge: 3000
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName


  PrivateHostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HostingBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Join ["", ["arn:aws:s3:::", !Ref HostingBucket, "/*"]]
            Principal:
              CanonicalUser: !GetAtt HostingOriginAccessIdentity.S3CanonicalUserId

  HostingOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "CloudFrontOriginAccessIdentityConfig"

  HostingCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: !Sub "${ProjectIdentifierName}HostingS3Bucket"
            DomainName: !GetAtt HostingBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Join ["", ["origin-access-identity/cloudfront/", !Ref HostingOriginAccessIdentity]]
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 400
            ResponseCode: 200
            ResponsePagePath: "/"
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/"
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/"
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 60
          TargetOriginId: !Sub "${ProjectIdentifierName}HostingS3Bucket"
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "index.html"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref ProjectIdentifierName

Outputs:
  HostingBucketName:
    Description: "Hosting bucket name"
    Value: !Ref HostingBucket
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt HostingBucket.WebsiteURL
  HostingBucketSecureURL:
    Description: Name of S3 bucket to hold website content
    Value:
      !Join:
        - ""
        - - "https://"
          - !GetAtt HostingBucket.DomainName
  HostingCloudFrontDistributionID:
    Value: !Ref HostingCloudFrontDistribution
  HostingCloudFrontDomainName:
    Value: !GetAtt HostingCloudFrontDistribution.DomainName
  HostingCloudFrontSecureURL:
    Value:
      !Join:
        - ""
        - - "https://"
          - !GetAtt HostingCloudFrontDistribution.DomainName

